name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: apk update && apk add make && make
      
