name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/podman/stable
    steps:
    - uses: actions/checkout@v3
    - name: Build the Podman image
      run: yum install -y make && make
      
