name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: apk update && apk add make && make
      
